# Generated by Django 4.0.4 on 2022-10-18 08:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('anhdaidien', models.ImageField(null=True, upload_to='users')),
                ('la_khach_hang', models.BooleanField(default=False)),
                ('sdt', models.CharField(max_length=10, null=True, unique=True)),
                ('cmnd', models.CharField(max_length=12, null=True, unique=True)),
                ('tuoi', models.CharField(default=0, max_length=3)),
                ('ngay_sinh', models.DateField(null=True)),
                ('dia_chi', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('gioi_tinh', models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')], default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('hoat_dong', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('gia', models.CharField(max_length=30)),
                ('hinh_anh', models.ImageField(null=True, upload_to='diadiem')),
                ('ngay_khoi_hanh', models.CharField(max_length=100)),
                ('chuyen_di', models.CharField(max_length=150)),
                ('phuong_tien', models.CharField(max_length=100)),
                ('mieu_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HangMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiemDuLich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('hoat_dong', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('hinh_anh_ddl', models.ImageField(null=True, upload_to='diemdulich')),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diemdulichs', to='dulichapp.diadiem')),
            ],
            options={
                'unique_together': {('ten', 'tour')},
            },
        ),
        migrations.AddField(
            model_name='diadiem',
            name='hang_muc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dulichapp.hangmuc'),
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danh_gia', models.PositiveSmallIntegerField(default=0, max_length=5)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('diemdl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dulichapp.diemdulich')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('hoat_dong', models.BooleanField(default=True)),
                ('diemdl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thembinhluans', to='dulichapp.diemdulich')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='diadiem',
            unique_together={('ten', 'hang_muc')},
        ),
    ]
