# Generated by Django 4.0.4 on 2022-09-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dulichapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiemDuLich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True)),
                ('hoat_dong', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('hinh_anh', models.ImageField(null=True, upload_to='diemdulich')),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diemdulichs', to='dulichapp.diadiem')),
            ],
            options={
                'unique_together': {('ten', 'tour')},
            },
        ),
    ]
