# Generated by Django 4.0.4 on 2022-10-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dulichapp', '0002_diadiem_nguoi_dung_alter_binhluan_nguoi_dung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tuoi',
        ),
    ]
