# Generated by Django 4.0.4 on 2022-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulichapp', '0003_alter_diadiem_ngay_khoi_hanh_alter_diadiem_ten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diadiem',
            name='hinh_anh',
            field=models.ImageField(null=True, upload_to='diadiem/%Y/%M'),
        ),
    ]
