# Generated by Django 4.0.4 on 2022-10-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulichapp', '0004_alter_diadiem_hinh_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diadiem',
            name='hinh_anh',
            field=models.ImageField(null=True, upload_to='diadiem/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='diemdulich',
            name='hinh_anh',
            field=models.ImageField(null=True, upload_to='diadiem/%Y/%m'),
        ),
    ]
