# Generated by Django 4.0.4 on 2022-10-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dulichapp', '0004_alter_danhgia_danh_gia_dattour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dattour',
            name='thanh_toan',
        ),
        migrations.AddField(
            model_name='dattour',
            name='hoa_don_mail',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('thanh_toan', models.IntegerField(choices=[(0, 'Tại quầy lấy vé'), (1, 'ViettelPay'), (2, 'Momo'), (3, 'ZaloPay')], default=0)),
                ('dat_tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dulichapp.dattour')),
            ],
        ),
    ]
