# Generated by Django 4.0.4 on 2022-10-17 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dulichapp', '0005_alter_diadiem_hinh_anh_alter_diemdulich_hinh_anh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='diemdulich',
            name='hinh_anh',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vaitro',
        ),
        migrations.AddField(
            model_name='diemdulich',
            name='hinh_anh_ddl',
            field=models.ImageField(null=True, upload_to='diemdulich'),
        ),
        migrations.AddField(
            model_name='user',
            name='cmnd',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dia_chi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gioi_tinh',
            field=models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='la_khach_hang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ngay_sinh',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sdt',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tuoi',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='diadiem',
            name='hinh_anh',
            field=models.ImageField(null=True, upload_to='diadiem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='anhdaidien',
            field=models.ImageField(null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danh_gia', models.PositiveSmallIntegerField(default=0, max_length=5)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('diemdl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dulichapp.diemdulich')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('hoat_dong', models.BooleanField(default=True)),
                ('diemdl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thembinhluans', to='dulichapp.diemdulich')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
